#!/usr/bin/env bash
# Self-contained installer: Python backend, Node frontend, and blackbox_decode.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
BACKEND="$ROOT/backend"
FRONTEND="$ROOT/frontend"
VENV="$BACKEND/.venv"
TOOLS_DIR="$ROOT/tools"
BB_SRC="$TOOLS_DIR/blackbox-tools-src"
BB_BIN="$TOOLS_DIR/bin"
BB_DECODE="$BB_BIN/blackbox_decode"
BB_DECODE_INAV="$BB_BIN/blackbox_decode_INAV"
BB_REPO="https://github.com/betaflight/blackbox-tools.git"
ENV_FILE="$ROOT/.pidbox.env"

echo "==> PIDToolBox install (self-contained)"
echo "    Project root: $ROOT"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: '$1' not found." >&2
    case "$1" in
      gcc|make)
        echo "       Install build tools, e.g.: sudo apt-get install -y build-essential git" >&2
        ;;
      git)
        echo "       Install git, e.g.: sudo apt-get install -y git" >&2
        ;;
    esac
    exit 1
  fi
}

write_env_file() {
  cat >"$ENV_FILE" <<EOF
# Generated by install.sh — sourced by start.sh
PIDBOX_ROOT=$ROOT
BLACKBOX_DECODE=$BB_DECODE
BLACKBOX_DECODE_INAV=$BB_DECODE_INAV
EOF
  echo "==> Wrote $ENV_FILE"
}

install_blackbox_decode() {
  echo "==> Installing blackbox_decode (Betaflight blackbox tools)"
  need_cmd git
  need_cmd make
  need_cmd gcc

  mkdir -p "$BB_BIN"

  if [[ -x "$BB_DECODE" ]]; then
    echo "    Already built: $BB_DECODE"
  else
    if [[ ! -d "$BB_SRC/.git" ]]; then
      echo "    Cloning $BB_REPO ..."
      git clone --depth 1 "$BB_REPO" "$BB_SRC"
    else
      echo "    Updating blackbox-tools source ..."
      git -C "$BB_SRC" fetch --depth 1 origin master 2>/dev/null || git -C "$BB_SRC" fetch --depth 1 origin main 2>/dev/null || true
      git -C "$BB_SRC" pull --ff-only 2>/dev/null || true
    fi

    echo "    Building blackbox_decode (this may take a minute) ..."
    make -C "$BB_SRC" clean >/dev/null 2>&1 || true
    make -C "$BB_SRC" obj/blackbox_decode

    install -m 755 "$BB_SRC/obj/blackbox_decode" "$BB_DECODE"
    echo "    Installed: $BB_DECODE"
  fi

  # INAV uses the same decoder in most setups; symlink for compatibility with PIDscope naming.
  ln -sf "$BB_DECODE" "$BB_DECODE_INAV"
  echo "    Linked: $BB_DECODE_INAV -> blackbox_decode"

  "$BB_DECODE" --help >/dev/null 2>&1 || "$BB_DECODE" 2>&1 | head -1 || true
}

need_cmd python3
need_cmd pip3
need_cmd node
need_cmd npm

PY_VERSION="$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
PY_MAJOR="$(python3 -c 'import sys; print(sys.version_info.major)')"
PY_MINOR="$(python3 -c 'import sys; print(sys.version_info.minor)')"
if [[ "$PY_MAJOR" -lt 3 ]] || [[ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 11 ]]; then
  echo "ERROR: Python 3.11+ required (found $PY_VERSION)." >&2
  exit 1
fi

echo "==> Python $PY_VERSION, Node $(node -v), npm $(npm -v)"

install_blackbox_decode
write_env_file

echo "==> Installing backend (Python venv + dependencies)"
cd "$BACKEND"
if [[ ! -d "$VENV" ]]; then
  python3 -m venv "$VENV"
fi
# shellcheck source=/dev/null
source "$VENV/bin/activate"
python -m pip install --upgrade pip wheel setuptools
pip install -e ".[dev]"

echo "==> Installing frontend (npm dependencies)"
cd "$FRONTEND"
if [[ -f package-lock.json ]]; then
  npm ci
else
  npm install
fi

echo "==> Generating golden test fixtures"
cd "$BACKEND"
# shellcheck source=/dev/null
source "$VENV/bin/activate"
python tests/export_golden.py

echo "==> Running backend tests"
pytest -q

echo "==> Building frontend"
cd "$FRONTEND"
npm run build

echo ""
echo "Install complete."
echo "  Start the app:     ./start.sh"
echo "  Stop the app:      ./kill.sh"
echo "  Backend API:       http://localhost:8000"
echo "  Frontend UI:       http://localhost:5173"
echo "  blackbox_decode:   $BB_DECODE"
